classDiagram
    direction BT
    View --> ViewModel: Observes
    View --> UserService
    UserService ..> Model
    UserServiceNode ..|> UserService
    UserRepository --> Model
    UserService --> ViewModel
    NodeApi --> ApiModel
    UserRepositoryNode ..|> UserRepository
    UserRepositoryNode --> NodeApi
    UserRepositoryNode ..> ApiModel

    class View {
    }
    class ViewModel {
    }
    class UserService {
        <<Interface>>
        GetModelWithSpecificFields(): ViewModel
    }
note for UserService "Uses Reposistory \nto convert Model\nto ViewModel"

    class UserServiceNode {
    }
    class Model {
    }
    class UserRepository {
        <<interface>>
        get(): Model
    }
    
note for UserRepository "Uses NodeApi layer\nto convert ApiModel\nto Model"
    class NodeApi {
        get(): ApiModel
    }
    
