classDiagram
    direction BT
    View --> ViewModel: Observes
    View --> Service
    Service ..> Model
    Service --> ViewModel

    class View {
    }


    class Service {
        <<Interface>>
        GetModelWithSpecificFields(): ViewModel
    }

    class ViewModel {
    }

    class Model {
    }
