sequenceDiagram
View->>+ViewModel: Bind observer
    View-->>+Service:Request for data for a specific view
    Service->>+Repository: Request for model
    Repository->>+API: Request data
    API->>+HTTPClient: Perform HTTP request to server
    HTTPClient-->>-API: 
    API-->>-Repository: Return data as JSON string
    Repository-->>Repository: Serialise JSON to Model
    Repository-->>-Service: Return model
    Service-->>-ViewModel: Update ViewModel from Model
    ViewModel-->>ViewModel: Update observers
    ViewModel-->>View: Update observer
    View-->>View: Update View values
